### ISSUE TITLE
add ibek ioc work-on <support module> function

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#136]
This will:

- move support module to /repos
- soft link its original location to its new location
- checkout a new branch in the repo

optionally not make a copy but instead use an existing clone in /repos (in which case a rebuild of this module should be executes)

(extracted from a comment in #71)

**Comment by GDYendell** [comment]
Is this different to #123 ?

**Comment by gilesknap** [comment]
its a duplicate. of #123 

However - I note I seem to have changed my approach from updating a RELEASE file to using a symlink.

Which do we prefer? The release file approach is more explicit and puts something in your generic IOC repo that will break it if you push it (which is good). So I think I prefer that/

**Comment by gilesknap** [comment]
closing as duplicate #123
