### ISSUE TITLE
Support schema should have union of args with discriminator

### ISSUE THREAD

**Issue by coretl** [epics-containers/ibek#150]
https://github.com/epics-containers/ibek/blob/54ae30d47ca12f86a084b2f37afc2e8638bcd2a8/src/ibek/support.py#L190-L192

Was expecting to see a discriminator here...

**Comment by coretl** [comment]
I was expecting something like:

https://github.com/epics-containers/ibek/blob/54ae30d47ca12f86a084b2f37afc2e8638bcd2a8/src/ibek/ioc.py#L175-L181

**Comment by coretl** [comment]
What happens if you squash it?
```python
discriminated = Annotated[Union[tuple(Arg.__subclasses__())], Field(discriminator="type")]  # type: ignore 
args: Sequence[discriminated] = Field(  # type: ignore 
    description="The arguments IOC instance should supply", default=() 
) 
```

**Comment by gilesknap** [comment]
I'm struggling to make this work. The error seems to say 'the annotated member is not annotated'.

In IOC we are dealing with dynamic classes and it just works, even though it looks mighty similar.

Is there an issue that you are aware of that this lack of correct discrimination is causing?

**Comment by coretl** [comment]
This just means the schema will give less descriptive error messages (rather than `type: int` required `int` default, it will say `{"type": "int", "default": "blah", ...}` doesn't match <some big union statement>.

**Comment by gilesknap** [comment]
OK, I'll leave this for now but keep the ticket open.

**Comment by gilesknap** [comment]
We sorted this one some time ago:
```python

    def make_ioc_model(self, entity_models: List[Type[Entity]]) -> Type[IOC]:
        """
        Create an IOC derived model, by setting its entities attribute to
        be of type 'list of Entity derived classes'.

        Also instantiate any SubEntities at this time
        """

        entity_union = Union[tuple(entity_models)]  # type: ignore
        discriminated = Annotated[entity_union, Field(discriminator="type")]  # type: ignore

        class NewIOC(IOC):
            entities: Sequence[discriminated] = Field(  # type: ignore
                description="List of entities this IOC instantiates"
            )

        return NewIOC
```
