### ISSUE TITLE
Proxy Pods for non native IOCs

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#185]
This concerns IOC's that run in RTEMS or Windows or potentially any other target architecture that is not native to the Kubernetes cluster.

To allow the management of these to look as similar as possible to native Linux IOCs we propose running proxy Pods that:

- Copy the IOC binaries and config to a shared file system accessible from the target.
- remotely control the target hardware, inducing it to launch said binaries and find said config
- attach the console of the resulting ioc to the stdio of the pod. Thus attaching and logging the IOC appears identical to Linux IOC's.

These features should be embedded into the runtime target for generic IOC's that are targeting non-native architecture. These targets will contain the minimised built assets just like native IOCs, but also the code to facilitate proxy features.

The above should be implemented in python and I propose they are added to ibek for the following reasons:

- ibek is needed already in the runtime targets to convert IOC.yaml to runtime assets.
- there is an additional proxy requirement for Windows during build time as we will be sending the compilation tasks to a Windows build server. Given that ibek is available during build and runtime this seems like a good fit.

QUESTION:
I'm struggling to think of a nice generic way to configure the windows server for build time. One way would be to have a DLS specific base container with our build server name hard coded in. This is possible as such builds will be internal only. But if prefer a more configurable solution.

**Comment by gilesknap** [comment]
Re windows build server. I think this can be part of the config of the gitlab runner and thus be passed into the build via environment variables.

**Comment by coretl** [comment]
I think this all sounds sensible

**Comment by gilesknap** [comment]
This has been done in a separate repo for now https://github.com/epics-containers/rtems-proxy.

My thought is that it belongs in a separate repo because the release cadence will be higher later in the project and changing ibek requires rebuilding the entire generic IOC whereas rtems-proxy can be installed at the end of the developer build.

Will revisit the possibility of merging these once everything is bedded in!
