### ISSUE TITLE
Add option to recursively clone submodules in ibek support git-clone

### ISSUE THREAD

**Issue by ulrikpedersen** [epics-containers/ibek#190]
I found myself having to drop out of the convenient `ibek support git-clone` command in my first ibek-support adventure because the support module uses git submodules to pull in an external dependency.

Would it be possible to add an option to the `git-clone` function to recursively clone submodules? The equivalent of `git clone --recurse-submodules`...

**Comment by gilesknap** [comment]
Yes that should definitely be in the command - making a new more general issue for this:  https://github.com/epics-containers/ibek/issues/194
