### ISSUE TITLE
trailing slash on git org

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#204]
I just got caught out by this (again)

```bash
ibek support git-clone ${NAME} ${VERSION} --org https://gitlab.diamond.ac.uk/controls/support
```

Gets auth error because it is looking for a non-existent repo.

It makes sense for ibek to add a trailing slash to org if one is not supplied. This then gets the intended git url.

**Comment by marcelldls** [comment]
> I just got caught out by this (again)
> 
> ```shell
> ibek support git-clone ${NAME} ${VERSION} --org https://gitlab.diamond.ac.uk/controls/support
> ```
> 
> Gets auth error because it is looking for a non-existent repo.
> 
> It makes sense for ibek to add a trailing slash to org if one is not supplied. This then gets the intended git url.

Agreed
