### ISSUE TITLE
Merge module.py into ibek

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#32]
module.py provides some functions for building the generic-ioc containers.

both ibek and module.py now reside in epics-base container, see https://github.com/epics-containers/epics-base/blob/main/support/module.py

It would make sense to merge the functions of module.py into ibek as it is the 'in container' home of python things to support the building  of support modules.

Not urgent.

**Comment by gilesknap** [comment]
This feature should add the ability for ibek to build the src/Makefile for you like builder currently does.

This means adding a whole extra part to the schema to describe what iocLIB and iocDBD entries need to be added to an IOCs makefile in order to support the module that you are adding.

This brings ibek up to a similar status to Builder and means it gets used at container build time as well as container runtime.

**Comment by niamhdougan** [comment]
After #37 and module.py iterations

**Comment by gilesknap** [comment]
NOTE: we are considering separating 
- generic IOC build process
- IOC instance instantiation

ibek is the latter and perhaps module.py is the basis for the latter.

**Comment by gilesknap** [comment]
closing - see https://github.com/epics-containers/ibek/issues/71#issuecomment-1708059237
