### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#34]
Would it be possible to provide Enum Types to constrain the values of args.

e.g. We could do with them in this ASYN def file
https://github.com/epics-containers/ibek/blob/a82a480637a038f13209f0c57cb77b60e45b03b8/tests/samples/yaml/asyn.ibek.defs.yaml#L37-L50

**Comment by niamhdougan** [comment]
After #37

**Comment by gilesknap** [comment]
Is using a magic string in the description the best way to do this?

**Comment by gilesknap** [comment]
do before J20

**Comment by gilesknap** [comment]
fixed in #92
