### ISSUE TITLE
changes to ibek-defs

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ibek#71]
We need a way to provide versioning of ibek.support.yaml files and patch files. After discussion with @coretl we have the following approach to try out:

(examples below for the asyn support module)
 
- the repo ibek-defs will become 2 repos: 
  - ibek-patch:
  
    - this contains patch script `asyn.sh` as before and any other files this needs to refer to
    - if breaking changes are made for e.g. asyn R4-44-2, then this file is copied to `asyn<R4-44-2.sh`
    - then the changes are made to the original `asyn.sh`
    - explicit copies into `/ctools` of the `ibek-patch/asyn` folder will be performed before each install (as before for ibek-defs)
    - `modules.py install` will automatically execute the patch file that is relevant based on the version of asyn in its 3rd argument
    - invocations of modules.py install will add to a file `/repos/epiics/support/modules.json` which will list the versions of modules 
       installed by modules.py

  - ibek-yaml:

   - contains `asyn.ibek.support.yaml`
   - also will contain previous versions of the file using `asyn<R4-44-2.ibek.support.yaml` naming convention
   - after all support module install and compiles are complete we copy ibek-support into the container at repos/ibek-support
   - a new modules.py command `add-yaml` will soft link yaml files into each of the support modules at e.g. `/repos/epics/support/asyn/ibek/asyn.ibek.support.yaml`
   - the file modules.json is used to determine which version of the yaml file is linked.
   - if the ibek folder already exists in the support module then this step does nothing as that is assumed to have a `support.yaml` file that versions with the support module.

- both of thes repos are added to every ioc-XXX using git submodules.

**Comment by gilesknap** [comment]
@tom one issue is that we have a global patch file

_globals/global.sh

![image](https://github.com/epics-containers/ibek/assets/964827/994819ad-d601-43e3-809d-bcb615ec17d3)

which is a nice place to put stuff you always want. At present it looks like this:
```bash
#!/bin/bash

# For RTEMS builds, avoid also building for the host architecture

if [[ $TARGET_ARCHITECTURE == "rtems" ]]; then
    echo Setting RTEMS build to target the crosscompile only ...

    echo >> configure/CONFIG_SITE.Common.linux-x86_64
    echo "VALID_BUILDS=Host" >> configure/CONFIG_SITE.Common.linux-x86_64
fi
```

**Comment by gilesknap** [comment]
@coretl if we are going to submodule both repos would it not be simpler to have a single repo with subfolders?

Managing sync of submodules between multiple iocs is already a little fiddly without having two to manage.

**Comment by gilesknap** [comment]
A further discussion with @coretl 
![image](https://github.com/epics-containers/ibek/assets/964827/cbb51141-4e6a-4c3d-8593-487752c46278)

Ideas:
- switch to using /workspace inside of the devcontainer instead of /scratch/xxxxx as this is confusing
- stick with a single repo for ibek-defs and use subfolders to split the stages at which files are used @tom I have made up some folder names here - feel free to suggest alternatives.
  - generic: for install script and patch files (and maybe for something that lists the DBD and LIB files)
  - instance: for the xxx.ibek.support.yaml
- have internal and external defs repos gh-ibek-defs and dls-ibek-defs
- in container build the support module build lines now look like this
```
COPY gh-ibek-defs/asyn/generic /workspace/gh-ibek-defs/asyn
RUN  /workspace/gh-ibek-defs/asyn/install.sh 4-28
    @coretl above is what we said but I'm now thinking we should keep `modules.py install` (`ibek install`) and have it auto-call a patch file which is version savvy. Then `ibek install` can do JSON file things etc.
RUN make -C ${SUPPORT}/asyn -j $(nproc)
```

- Once all support modules are built clone the ibek defs folders into /repos and use the command `ibek build-ioc` which will read the JSON list of above installed support and:
  - Add entries in the make file for dbd and libs
  - (in future make some device screens)
  - soft link a ibek.support.yaml file into each support module e.g.
    - /repos/gh-ibek-defs/asyn/instance/asyn.ibek.support.yaml --> /repos/epics/support/asyn/ibek/asyn.ibek.support.yaml
  - the soft link only happens if the module does not already define its own support YAML

**Comment by gilesknap** [comment]
Make this work:
```sh
/workspace/module-install-gh/asyn/install.sh 4-22
# which does:
# - clone, checkout
# - patch
# - put LIBS and DBDs in makefile
# - link ibek defs to the right place
# - link pvi files to the right place
# - all the things I put in that excalidraw
# - ...
```
Before J20

**Comment by gilesknap** [comment]
This implies that module.py is deprecated or becomes a script that is called from install.sh.
Hence closing #32

**Comment by gilesknap** [comment]
install.sh is going to need to replace the functions of module.py (and add new functions re LIBS/OPIs etc). It should call to some global implementation for common functions (and these could be python or bash).

IMPORTANT: rebuilding a container should always work so changes to these common functions should not break old generic-ioc builds.

THIS MEANS: on of the following: 

1.   the global functions are versioned in ibek-defs somehow
2.   are part of the epics-base container source (like module.py was).
3.   are part of the generic-ioc container source and are added to by updating ioc-template (this also means each generic ioc build can customize its 

It is true to say that because we use submodules, simply rebuilding a container should always work if you do hot update submodules. For this reason 1, could be as simple as using git for versioning. That leaves developers open to needing to sort out incompatilities when just wanting to add a new support module.

3 - gives the most flexibility but is it too anarchic?

@coretl @GDYendell - Any thoughts on 1-3 above?

**Comment by coretl** [comment]
I vote 2, as any module could be installed in any generic IOC then this seems least error prone

**Comment by gilesknap** [comment]
2 is the least error prone but the most expensive every time we make a change. I don't get your comment about 'any module'?

**Comment by coretl** [comment]
Option 1 then

**Comment by gilesknap** [comment]
After discussion we have voted for 1.

- this means that the global functions are versioned along side the install scripts that use them
- it's really easy to add new features on the fly
- we can have CI to verify that you have not broken the global functions for any support module.
- the CI should ensure that adopting the latest defs into a generic IOC should never break.

**Comment by gilesknap** [comment]
This whiteboard summarises the latest thinking on this subject.
![image](https://github.com/epics-containers/ibek/assets/964827/fae1a09a-b62c-4b8d-b877-86015330d1c3)

**Comment by gilesknap** [comment]
Changes to ibek-support (previously ibek-defs) are all done and working for ADSimDetector.

Still to do:

- add the 'workon' command to ec 
- set all the support folders to readonly in the container (prod style)
- soft linking of the bob/pvi/yaml
- ioc-xxx projects to publish their ioc schema as release asset

**Comment by gilesknap** [comment]
Created separate issues for the remaining two points above
